/**
 * Codegen: turn a `LaunchSpec` into the exact TypeScript a builder runs to put
 * the config on chain. The output is deliberately boring — copy, paste, ship.
 *
 * The shape of the generated file is verified by `tests/codegen.test.ts` and by
 * compiling the output, because a launch script that does not run is worse than
 * no launch script.
 */
import { liquidityWeightsFor, leftoverFor } from './build';
import type { LaunchSpec } from './types';

function num(value: number): string {
  return value.toLocaleString('en-US').replace(/,/g, '_');
}

const KNOWN_MINTS: Record<string, string> = {
  SOL: 'So11111111111111111111111111111111111111112',
  USDC: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
};

function quoteMintOf(spec: LaunchSpec): string {
  return KNOWN_MINTS[spec.quoteAsset] ?? spec.quoteAsset;
}

/** A quote asset the SDK does not ship a mint constant for. */
function isCustomQuote(spec: LaunchSpec): boolean {
  return !(spec.quoteAsset in KNOWN_MINTS);
}

/** `client.partner.createConfig()` script for this launch spec. */
export function toCreateConfigScript(spec: LaunchSpec): string {
  const shape = spec.curveShape ?? 'marketCap';
  const weighted = shape !== 'marketCap';

  const builder = weighted
    ? `buildCurveWithLiquidityWeights({
${baseParams(spec)}

  // ${shape} curve: sixteen weighted segments. Weights are relative liquidity
  // depth per segment, so this is what makes the price move the way it does.
  liquidityWeights: [${liquidityWeightsFor(shape).map((w) => w.toFixed(4)).join(', ')}],
})`
    : `buildCurveWithMarketCap({
${baseParams(spec)}
})`;

  return `/**
 * ${spec.name} — generated by CurveCraft
 * ${spec.description ?? 'Meteora Dynamic Bonding Curve launch config.'}
 *
 *   npm i @meteora-ag/dynamic-bonding-curve-sdk @solana/web3.js
 *   RPC_URL=https://api.mainnet-beta.solana.com KEYPAIR=./id.json npx tsx launch.ts
 *
 * Compile-time check: this file type-checks against the SDK it imports.
 */
import { readFileSync } from 'node:fs';
import { Connection, Keypair, PublicKey } from '@solana/web3.js';
import {
  ActivationType,
  BaseFeeMode,
  CollectFeeMode,
  DynamicBondingCurveClient,
  MigrationFeeOption,
  MigrationOption,
  TokenAuthorityOption,
  TokenDecimal,
  TokenType,
  ${weighted ? 'buildCurveWithLiquidityWeights' : 'buildCurveWithMarketCap'},
} from '@meteora-ag/dynamic-bonding-curve-sdk';

async function main() {
  const connection = new Connection(
    process.env.RPC_URL ?? 'https://api.mainnet-beta.solana.com',
    'confirmed',
  );
  const client = DynamicBondingCurveClient.create(connection, 'confirmed');

  const payer = Keypair.fromSecretKey(
    Uint8Array.from(JSON.parse(readFileSync(process.env.KEYPAIR ?? './id.json', 'utf8')) as number[]),
  );

  // The config lives in its own account, so it needs its own keypair.
  const configKeypair = Keypair.generate();

  const curveConfig = ${builder};

  const transaction = await client.partner.createConfig({
    ...curveConfig,
    config: configKeypair.publicKey,
    feeClaimer: payer.publicKey,
    leftoverReceiver: payer.publicKey,
    payer: payer.publicKey,
    quoteMint: new PublicKey('${quoteMintOf(spec)}'),${isCustomQuote(spec) ? ` // TODO: replace with the ${spec.quoteAsset} mint address` : ''}
  });

  transaction.feePayer = payer.publicKey;
  transaction.recentBlockhash = (await connection.getLatestBlockhash()).blockhash;
  transaction.sign(payer, configKeypair);

  const signature = await connection.sendRawTransaction(transaction.serialize());
  await connection.confirmTransaction(signature, 'confirmed');

  console.log('config:   ', configKeypair.publicKey.toBase58());
  console.log('signature:', signature);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
`;
}

/** Quote decimals as a literal number, since TokenDecimal has no constant for 8 or 18. */
function quoteDecimalsLiteral(spec: LaunchSpec): string {
  const decimals = spec.quoteDecimals ?? (spec.quoteAsset === 'USDC' ? 6 : 9);
  return decimals === 6 ? 'TokenDecimal.SIX' : decimals === 9 ? 'TokenDecimal.NINE' : String(decimals);
}

function baseParams(spec: LaunchSpec): string {
  const shape = spec.curveShape ?? 'marketCap';
  return `    token: {
      tokenType: TokenType.SPLToken,
      tokenBaseDecimal: TokenDecimal.SIX,
      tokenQuoteDecimal: ${quoteDecimalsLiteral(spec)},
      tokenAuthorityOption: TokenAuthorityOption.CreatorUpdateAuthority,
      totalTokenSupply: ${num(spec.totalSupply)},
      leftover: ${num(leftoverFor(spec))},
    },
    fee: {
${feeBlock(spec)}
      dynamicFeeEnabled: ${spec.dynamicFee.enabled},
      collectFeeMode: CollectFeeMode.${
        spec.collectFeeMode === 'output' ? 'OutputToken' : 'QuoteToken'
      },
      creatorTradingFeePercentage: ${spec.creatorTradingFeePercentage},
      poolCreationFee: 0,
      enableFirstSwapWithMinFee: false,
    },
    migration: {
      migrationOption: MigrationOption.${
        spec.migrationTarget === 'dammV1' ? 'MET_DAMM' : 'MET_DAMM_V2'
      },
      migrationFeeOption: MigrationFeeOption.FixedBps${spec.migrationFeePreset},
      migrationFee: { feePercentage: 0, creatorFeePercentage: 0 },
    },
    liquidityDistribution: {
      partnerPermanentLockedLiquidityPercentage: ${
        spec.liquidityDistribution?.partnerPermanentLockedLiquidityPercentage ?? 0
      },
      partnerLiquidityPercentage: ${spec.liquidityDistribution?.partnerLiquidityPercentage ?? 0},
      creatorPermanentLockedLiquidityPercentage: ${
        spec.liquidityDistribution?.creatorPermanentLockedLiquidityPercentage ?? 10
      },
      creatorLiquidityPercentage: ${spec.liquidityDistribution?.creatorLiquidityPercentage ?? 90},
    },
    lockedVesting: {
      totalLockedVestingAmount: ${spec.lockedVesting?.totalLockedVestingAmount ?? 0},
      numberOfVestingPeriod: ${spec.lockedVesting?.numberOfVestingPeriod ?? 0},
      cliffUnlockAmount: ${spec.lockedVesting?.cliffUnlockAmount ?? 0},
      totalVestingDuration: ${spec.lockedVesting?.totalVestingDuration ?? 0},
      cliffDurationFromMigrationTime: ${
        spec.lockedVesting?.cliffDurationFromMigrationTime ?? 0
      },
    },
    activationType: ActivationType.Timestamp,
    initialMarketCap: ${num(spec.initialMarketCap)},
    migrationMarketCap: ${num(spec.migrationMarketCap)},
    // curve shape: ${shape}
`;
  }

function feeBlock(spec: LaunchSpec): string {
  if (spec.feeMode === 'rateLimiter') {
    return `    baseFeeParams: {
      baseFeeMode: BaseFeeMode.RateLimiter,
      rateLimiterParam: {
        baseFeeBps: ${spec.rateLimiter?.baseFeeBps ?? spec.feeSchedule.startingFeeBps},
        feeIncrementBps: ${spec.rateLimiter?.feeIncrementBps ?? 100},
        referenceAmount: ${spec.rateLimiter?.referenceAmount ?? 1},
        maxLimiterDuration: ${spec.rateLimiter?.maxLimiterDurationSec ?? 3600},
      },
    },`.replace(/^/gm, '  ');
  }
  return `    baseFeeParams: {
      baseFeeMode: BaseFeeMode.${
        spec.feeMode === 'exponential' ? 'FeeSchedulerExponential' : 'FeeSchedulerLinear'
      },
      feeSchedulerParam: {
        startingFeeBps: ${spec.feeSchedule.startingFeeBps},
        endingFeeBps: ${spec.feeSchedule.endingFeeBps},
        numberOfPeriod: ${spec.feeSchedule.numberOfPeriods},
        totalDuration: ${spec.feeSchedule.totalDurationSec},
      },
    },`.replace(/^/gm, '  ');
}
