/**
 * Codegen: turn a `LaunchSpec` into the exact TypeScript a builder runs to put
 * the config on chain. The output is deliberately boring — copy, paste, ship.
 */
import type { LaunchSpec } from './types';

function num(value: number): string {
  return value.toLocaleString('en-US').replace(/,/g, '_');
}

/** `client.partner.createConfig()` script for this launch spec. */
export function toCreateConfigScript(spec: LaunchSpec): string {
  const quoteDec = spec.quoteAsset === 'USDC' ? 6 : 9;
  const feeBlock =
    spec.feeMode === 'rateLimiter'
      ? `      baseFeeParams: {
        baseFeeMode: BaseFeeMode.RateLimiter,
        rateLimiterParam: {
          baseFeeBps: ${spec.rateLimiter?.baseFeeBps ?? spec.feeSchedule.startingFeeBps},
          feeIncrementBps: ${spec.rateLimiter?.feeIncrementBps ?? 100},
          referenceAmount: ${spec.rateLimiter?.referenceAmount ?? 1},
          maxLimiterDuration: ${spec.rateLimiter?.maxLimiterDurationSec ?? 3600},
        },
      },`
      : `      baseFeeParams: {
        baseFeeMode: BaseFeeMode.${
          spec.feeMode === 'exponential' ? 'FeeSchedulerExponential' : 'FeeSchedulerLinear'
        },
        feeSchedulerParam: {
          startingFeeBps: ${spec.feeSchedule.startingFeeBps},
          endingFeeBps: ${spec.feeSchedule.endingFeeBps},
          numberOfPeriod: ${spec.feeSchedule.numberOfPeriods},
          totalDuration: ${spec.feeSchedule.totalDurationSec},
        },
      },`;

  return `/**
 * ${spec.name} — generated by CurveCraft
 * ${spec.description ?? 'Meteora Dynamic Bonding Curve launch config.'}
 *
 *   npm i @meteora-ag/dynamic-bonding-curve-sdk @solana/web3.js bn.js
 *   RPC_URL=https://... KEYPAIR=./id.json npx tsx launch.ts
 */
import { readFileSync } from 'node:fs';
import { Connection, Keypair } from '@solana/web3.js';
import {
  ActivationType,
  BaseFeeMode,
  CollectFeeMode,
  DynamicBondingCurveClient,
  MigrationFeeOption,
  MigrationOption,
  TokenAuthorityOption,
  TokenDecimal,
  TokenType,
  buildCurveWithMarketCap,
} from '@meteora-ag/dynamic-bonding-curve-sdk';

const connection = new Connection(process.env.RPC_URL!, 'confirmed');
const client = DynamicBondingCurveClient.create(connection, 'confirmed');

const payer = Keypair.fromSecretKey(
  Uint8Array.from(JSON.parse(readFileSync(process.env.KEYPAIR!, 'utf8'))) as number[],
);

const curveConfig = buildCurveWithMarketCap({
  token: {
    tokenType: TokenType.SPLToken,
    tokenBaseDecimal: TokenDecimal.SIX,
    tokenQuoteDecimal: ${quoteDec === 9 ? 'TokenDecimal.NINE' : '6'},
    tokenAuthorityOption: TokenAuthorityOption.CreatorUpdateAuthority,
    totalTokenSupply: ${num(spec.totalSupply)},
    leftover: 0,
  },
  fee: {
${feeBlock}
    dynamicFeeEnabled: ${spec.dynamicFee.enabled},
    collectFeeMode: CollectFeeMode.${
      spec.collectFeeMode === 'output' ? 'OutputToken' : 'QuoteToken'
    },
    creatorTradingFeePercentage: ${spec.creatorTradingFeePercentage},
    poolCreationFee: 0,
    enableFirstSwapWithMinFee: false,
  },
  migration: {
    migrationOption: MigrationOption.${
      spec.migrationTarget === 'dammV1' ? 'MET_DAMM' : 'MET_DAMM_V2'
    },
    migrationFeeOption: MigrationFeeOption.FixedBps${spec.migrationFeePreset},
    migrationFee: { feePercentage: 0, creatorFeePercentage: 0 },
  },
  liquidityDistribution: {
    partnerPermanentLockedLiquidityPercentage: ${
      spec.liquidityDistribution?.partnerPermanentLockedLiquidityPercentage ?? 0
    },
    partnerLiquidityPercentage: ${spec.liquidityDistribution?.partnerLiquidityPercentage ?? 0},
    creatorPermanentLockedLiquidityPercentage: ${
      spec.liquidityDistribution?.creatorPermanentLockedLiquidityPercentage ?? 0
    },
    creatorLiquidityPercentage: ${spec.liquidityDistribution?.creatorLiquidityPercentage ?? 100},
  },
  lockedVesting: {
    totalLockedVestingAmount: ${spec.lockedVesting?.totalLockedVestingAmount ?? 0},
    numberOfVestingPeriod: ${spec.lockedVesting?.numberOfVestingPeriod ?? 0},
    cliffUnlockAmount: ${spec.lockedVesting?.cliffUnlockAmount ?? 0},
    totalVestingDuration: ${spec.lockedVesting?.totalVestingDuration ?? 0},
    cliffDurationFromMigrationTime: ${
      spec.lockedVesting?.cliffDurationFromMigrationTime ?? 0
    },
  },
  activationType: ActivationType.Timestamp,
  initialMarketCap: ${num(spec.initialMarketCap)},
  migrationMarketCap: ${num(spec.migrationMarketCap)},
});

const { config } = await client.partner.createConfig({
  config: curveConfig,
  feeClaimer: payer.publicKey,
  leftoverReceiver: payer.publicKey,
  payer: payer.publicKey,
  quoteMint: new PublicKey('${spec.quoteAsset === 'USDC' ? 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v' : 'So11111111111111111111111111111111111111112'}'),
} as never);

console.log('config created:', config.toBase58());
`;
}
