/**
 * Launch report export.
 *
 * The studio is for iterating; a founder needs something to hand to a
 * co-founder, a sponsor or a community. This turns a design plus its analysis
 * into one markdown document: the config, what the pre-deploy check says, how it
 * behaves under each demand pattern, the graduation odds, and the script that
 * puts it on chain.
 */
import { CURVE_SHAPE_LABELS } from './build';
import { toCreateConfigScript } from './codegen';
import type { DemandModel, MonteCarloResult } from './montecarlo';
import type { AnalysisResult } from './analysis';
import type { LaunchSpec } from './types';

export interface ReportInput {
  spec: LaunchSpec;
  analysis: AnalysisResult;
  monteCarlo?: MonteCarloResult | null;
}

function fmt(value: number, digits = 2): string {
  if (!Number.isFinite(value)) return '—';
  if (Math.abs(value) >= 1_000_000) return `${(value / 1_000_000).toFixed(2)}M`;
  if (Math.abs(value) >= 1_000) return `${(value / 1_000).toFixed(2)}k`;
  return value.toFixed(digits);
}

function clock(seconds: number | null): string {
  if (seconds === null) return '—';
  const h = Math.floor(seconds / 3_600);
  const m = Math.round((seconds % 3_600) / 60);
  return h > 0 ? `${h}h ${m}m` : `${m}m`;
}

function feeRate(fees: number, volume: number): string {
  return volume > 0 ? `${((fees / volume) * 100).toFixed(2)}%` : '—';
}

function modelSummary(model: DemandModel): string {
  return [
    `buyers ≈ ${model.buyersMean} (σ ${model.buyersSigma})`,
    `buy size ≈ ${model.buyMean} (σ ${model.buySigma})`,
    `${Math.round(model.sniperProbability * 100)}% chance of a ${model.sniperBots}-bot sniper wave`,
    `${Math.round(model.whaleProbability * 100)}% chance of a whale (${Math.round(
      model.whaleDumpProbability * 100,
    )}% of those dump)`,
    `horizon ${clock(model.horizonSec)}`,
  ].join(' · ');
}

/** Markdown report for a designed launch. */
export function toLaunchReport({ spec, analysis, monteCarlo }: ReportInput): string {
  const { derived, runs, lint } = analysis;
  const quote = spec.quoteAsset;
  const shape = spec.curveShape ?? 'marketCap';

  const organic = runs[0];
  const sniper = runs[1];
  const organicFee = organic && organic.quoteVolume > 0 ? organic.tradingFees / organic.quoteVolume : 0;
  const sniperFee = sniper && sniper.quoteVolume > 0 ? sniper.tradingFees / sniper.quoteVolume : 0;
  const sniperPremium = organicFee > 0 ? ((sniperFee - organicFee) / organicFee) * 100 : null;

  const lines: string[] = [];

  lines.push(`# ${spec.name} — launch report`);
  lines.push('');
  lines.push(`_Generated by CurveCraft on ${new Date().toISOString().slice(0, 10)}._`);
  lines.push('');
  if (spec.description) {
    lines.push(spec.description);
    lines.push('');
  }

  lines.push('## The launch');
  lines.push('');
  lines.push('| Parameter | Value |');
  lines.push('|---|---|');
  lines.push(`| Quote asset | ${quote} |`);
  lines.push(`| Total supply | ${fmt(spec.totalSupply, 0)} tokens |`);
  lines.push(`| Curve shape | ${CURVE_SHAPE_LABELS[shape] ?? shape} |`);
  lines.push(`| Start market cap | ${fmt(spec.initialMarketCap)} ${quote} |`);
  lines.push(`| Graduation market cap | ${fmt(spec.migrationMarketCap)} ${quote} |`);
  lines.push(`| Raise to graduate | **${fmt(derived.migrationQuoteThreshold)} ${quote}** |`);
  lines.push(`| First fill price | ${derived.startPrice.toExponential(3)} ${quote} |`);
  lines.push(`| Graduation price | ${derived.migrationPrice.toExponential(3)} ${quote} |`);
  lines.push(`| Price multiple | ${(derived.migrationPrice / derived.startPrice).toFixed(1)}× |`);
  lines.push(`| Supply on the curve at graduation | ${fmt(derived.migrationSupply, 0)} tokens |`);
  lines.push(
    `| Fee schedule | ${spec.feeMode} · ${(spec.feeSchedule.startingFeeBps / 100).toFixed(2)}% → ${(
      spec.feeSchedule.endingFeeBps / 100
    ).toFixed(2)}% over ${clock(spec.feeSchedule.totalDurationSec)} (${spec.feeSchedule.numberOfPeriods} periods) |`,
  );
  lines.push(`| Dynamic fee | ${spec.dynamicFee.enabled ? 'enabled' : 'off'} |`);
  lines.push(
    `| Liquidity split | ${spec.liquidityDistribution?.creatorLiquidityPercentage ?? 90}% liquid · ${
      spec.liquidityDistribution?.creatorPermanentLockedLiquidityPercentage ?? 10
    }% permanently locked |`,
  );
  lines.push(`| Migration | ${spec.migrationTarget} · ${spec.migrationFeePreset} bps fee |`);
  lines.push('');
  lines.push(
    `Reading this: a market cap is a price multiplied by supply, so graduation means the curve has absorbed **${fmt(
      derived.migrationQuoteThreshold,
    )} ${quote}** and the price has moved ${(derived.migrationPrice / derived.startPrice).toFixed(
      1,
    )}×.`,
  );
  lines.push('');

  lines.push('## Pre-deploy check');
  lines.push('');
  lines.push(lint.ok ? '**Every program rule checked passes.**' : '**This config cannot be deployed yet.**');
  lines.push('');
  for (const item of lint.items) {
    const mark = item.level === 'error' ? '❌' : item.level === 'warning' ? '⚠️' : '✅';
    lines.push(`- ${mark} **${item.title}** — ${item.detail}`);
  }
  lines.push('');

  lines.push('## How it behaves under demand');
  lines.push('');
  lines.push('| Scenario | Peak market cap | Fees earned | Effective fee rate | Graduates at |');
  lines.push('|---|---|---|---|---|');
  for (const run of runs) {
    lines.push(
      `| ${run.scenarioName} | ${fmt(run.peakMarketCap)} ${quote} | ${fmt(run.tradingFees)} ${quote} | ${feeRate(
        run.tradingFees,
        run.quoteVolume,
      )} | ${run.graduatedAtSec === null ? 'does not graduate' : clock(run.graduatedAtSec)} |`,
    );
  }
  lines.push('');
  if (sniperPremium !== null) {
    lines.push(
      `**Sniper premium: ${sniperPremium > 0 ? '+' : ''}${sniperPremium.toFixed(
        1,
      )}%.** A sniper wave pays this much more per unit of volume than organic demand. Under ~5%, the fee schedule is not really taxing snipers; it is just charging everyone more.`,
    );
    lines.push('');
  }

  if (monteCarlo) {
    lines.push('## Graduation odds');
    lines.push('');
    lines.push(
      `${monteCarlo.runs} sampled demand paths (${modelSummary(monteCarlo.model)}), each priced fill-by-fill with the Meteora SDK.`,
    );
    lines.push('');
    lines.push('| Metric | p10 | p50 | p90 |');
    lines.push('|---|---|---|---|');
    lines.push(
      `| Fees earned (${quote}) | ${fmt(monteCarlo.fees.p10)} | ${fmt(monteCarlo.fees.p50)} | ${fmt(
        monteCarlo.fees.p90,
      )} |`,
    );
    lines.push(
      `| Effective fee rate | ${monteCarlo.feeRate.p10.toFixed(2)}% | ${monteCarlo.feeRate.p50.toFixed(
        2,
      )}% | ${monteCarlo.feeRate.p90.toFixed(2)}% |`,
    );
    lines.push(
      `| Peak market cap (${quote}) | ${fmt(monteCarlo.peakMarketCap.p10)} | ${fmt(
        monteCarlo.peakMarketCap.p50,
      )} | ${fmt(monteCarlo.peakMarketCap.p90)} |`,
    );
    lines.push('');
    lines.push(
      `**Graduation probability: ${(monteCarlo.graduationProbability * 100).toFixed(
        0,
      )}%** (${monteCarlo.graduated} of ${monteCarlo.runs} paths)${
        monteCarlo.graduationTimeP50 ? `, median time to graduate ${clock(monteCarlo.graduationTimeP50)}` : ''
      }.`,
    );
    lines.push('');
    lines.push(
      'The honest headline is the probability, not the median path: a launch either graduates or it does not, and the spread above is what you are actually exposed to.',
    );
    lines.push('');
  }

  lines.push('## Launch script');
  lines.push('');
  lines.push('```ts');
  lines.push(toCreateConfigScript(spec).trim());
  lines.push('```');
  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push(
    'Simulated with `@meteora-ag/dynamic-bonding-curve-sdk` — every fill is quoted by `client.pool.swapQuote2` and the pool is advanced exactly as the on-chain program advances it. No curve math is re-implemented.',
  );

  return lines.join('\n');
}
